import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar,Footer, InforCard, ServiceOverview,Capabilities} from "@/components";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "EAIS|Enterprise AI Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=GeistSans:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body
        className="relative">
        <Navbar/>
        {children}
        <InforCard/>
        <ServiceOverview/>
        <Capabilities/>
        <Footer/>
      </body>
    </html>
  );
}
